# Generated by Django 4.2.4 on 2023-08-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0003_alter_message_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_uname',
        ),
    ]
