# Generated by Django 4.2.4 on 2023-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0004_rename_sender_message_sender_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_uname',
            new_name='sender',
        ),
    ]
