# Generated by Django 4.2.4 on 2023-08-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0005_rename_sender_uname_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
