# Generated by Django 4.2.4 on 2023-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0006_user_has_completed_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_type',
            field=models.CharField(choices=[('Team', 'Team'), ('Public', 'Public'), ('Private', 'Private')], default='Team', max_length=255),
        ),
    ]
