# Generated by Django 4.2.4 on 2023-08-31 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0007_alter_chatgroup_group_id_alter_chatgroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(default='Member', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamManagement.team'),
        ),
    ]
