# Generated by Django 4.2.4 on 2023-09-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0008_groupmember_role_alter_chatgroup_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='resources/avatars/'),
        ),
    ]
