# Generated by Django 4.2.4 on 2023-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/team_images/'),
        ),
    ]
