# Generated by Django 4.2.4 on 2023-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=255)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
    ]
