# Generated by Django 4.2.4 on 2023-08-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeamManagement', '0001_initial'),
        ('ProjectExecution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManagement.team'),
        ),
    ]
