# Generated by Django 4.2.4 on 2023-08-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('prototype_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('prototype_name', models.CharField(max_length=255)),
                ('prototype_description', models.CharField(max_length=255)),
                ('prototype_file', models.FileField(blank=True, null=True, upload_to='prototype_files/')),
                ('tag', models.CharField(choices=[('Deleted', 'Deleted'), ('Normal', 'Normal')], default='Normal', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectExecution.project')),
            ],
            options={
                'db_table': 'Prototypes',
            },
        ),
    ]
