# Generated by Django 4.2.4 on 2023-08-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0004_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Normal', 'Normal')], default='Normal', max_length=255),
        ),
    ]
