# Generated by Django 4.2.4 on 2023-08-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0005_project_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='prototype_file',
        ),
        migrations.AddField(
            model_name='prototype',
            name='prototype_data_file',
            field=models.FileField(blank=True, null=True, upload_to='prototype_files/'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='prototype_style_file',
            field=models.FileField(blank=True, null=True, upload_to='prototype_files/'),
        ),
    ]
