# Generated by Django 4.2.4 on 2023-08-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0006_remove_prototype_prototype_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
