# Generated by Django 4.2.4 on 2023-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0007_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
