# Generated by Django 4.2.4 on 2023-09-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0008_doc_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/project_images/'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='prototype_data_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/prototype_files/'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='prototype_style_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/prototype_files/'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('Doc', 'Doc'), ('Folder', 'Folder')], default='Doc', max_length=255)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectExecution.doc')),
                ('parent_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectExecution.node')),
            ],
        ),
    ]
