# Generated by Django 4.2.4 on 2023-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0010_alter_prototype_prototype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='prototype_preview_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/prototype_previews/'),
        ),
    ]
