# Generated by Django 4.2.4 on 2023-09-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0011_prototype_prototype_preview_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='yjs_data',
            field=models.BinaryField(null=True),
        ),
    ]
