# Generated by Django 4.2.4 on 2023-09-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0012_doc_yjs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectExecution.project'),
        ),
    ]
