# Generated by Django 4.2.4 on 2023-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0014_alter_node_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
