# Generated by Django 4.2.4 on 2023-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectExecution', '0015_alter_node_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='editable_by_guests',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
