# Generated by Django 4.2.4 on 2023-08-31 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectExecution', '0008_doc_doc_name'),
        ('TeamManagement', '0008_groupmember_role_alter_chatgroup_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('group_chat', 'Group Chat Mention'), ('document', 'Document Mention'), ('system', 'System Notification')], max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectExecution.doc')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamManagement.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
